
export const GET_ANIME_LOADING = 'GET_ANIME_LOADING';
export const GET_ANIME_SUCCESS = 'GET_ANIME_SUCCESS';
export const GET_ANIME_ERROR = 'GET_ANIME_ERROR';

export const GET_ANIME_DETAILS_LOADING = 'GET_ANIME_DETAILS_LOADING'
export const GET_ANIME_DETAILS_SUCCESS = 'GET_ANIME_DETAILS_SUCCESS'
export const GET_ANIME_DETAILS_ERROR = 'GET_ANIME_DETAILS_ERROR'

export const GET_ANIME_CHARACTERS_LOADING = 'GET_ANIME_CHARACTERS_LOADING'
export const GET_ANIME_CHARACTERS_SUCCESS = 'GET_ANIME_CHARACTERS_SUCCESS'
export const GET_ANIME_CHARACTERS_ERROR = 'GET_ANIME_CHARACTERS_ERROR'

export const GET_ANIME_VOICE_CHARACTERS_LOADING = 'GET_ANIME_VOICE_CHARACTERS_LOADING'
export const GET_ANIME_VOICE_CHARACTERS_SUCCESS = 'GET_ANIME_VOICE_CHARACTERS_SUCCESS'
export const GET_ANIME_VOICE_CHARACTERS_ERROR = 'GET_ANIME_VOICE_CHARACTERS_ERROR'

export const GET_ANIME_STAFFS_LOADING = 'GET_ANIME_VOICE_STAFFS_LOADING'
export const GET_ANIME_STAFFS_SUCCESS = 'GET_ANIME_VOICE_STAFFS_SUCCESS'
export const GET_ANIME_STAFFS_ERROR = 'GET_ANIME_VOICE_STAFFS_ERROR'


export interface e {
    key: string
}

